import { Product } from "./types";
import { COLORS } from "./constants";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    favorite: true,
    name: "Pijama Algodón Dama",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 2,
    favorite: true,
    name: "Pijama Algodón Hombre",
    price: "S/.26.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 3,
    favorite: true,
    name: "Pijama Algodón Niño",
    price: "S/.17.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 4,
    favorite: true,
    name: "Pijama Algodón Niña",
    price: "S/.17.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 5,
    favorite: true,
    name: "Pijama Pima Dama",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.corn, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 6,
    favorite: true,
    name: "Pijama Pima Hombre",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.antike, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 7,
    name: "Pijama Pima Niño",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 8,
    name: "Pijama Pima Niña",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 9,
    name: "Pijama Franela Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 10,
    name: "Pijama Franela Hombre",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 11,
    favorite: true,
    name: "Pijama Franela Niño",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 12,
    name: "Pijama Franela Niña",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 13,
    favorite: true,
    name: "Pijama Polar Dama",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.coral, image: "images/products/orange-1.jpg" },
      { ...COLORS.barnie, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 14,
    name: "Pijama Polar Hombre",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.antike, image: "images/products/orange-1.jpg" },
      { ...COLORS.militaryGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 15,
    name: "Pijama Polar Niño",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 16,
    name: "Pijama Polar Niña",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 17,
    name: "Pijama Pantalón Largo M/ corta Algodón Dama",
    price: "S/.24.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 18,
    name: "Pijama Pantalón Largo M/corta Algodón Hombre",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 19,
    name: "Pijama Pantalón Largo M/corta Pima Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 20,
    name: "Pijama Pantalón Largo M/corta Pima Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 21,
    name: "Pijama Algodón Dama Chavo",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 22,
    name: "Pijama Pima Dama Chavo",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 23,
    name: "Pijama Short Algodón Dama",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 24,
    name: "Pijama Short Algodón Hombre",
    price: "S/.23.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 25,
    name: "Pijama Short Algodón Niño",
    price: "S/.15.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 26,
    name: "Pijama Short Algodón Niño",
    price: "S/.15.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 27,
    name: "Pijama Short Pima Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.corn, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 28,
    name: "Pijama Short Pima Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.antike, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 29,
    name: "Pijama Short Pima Niño",
    price: "S/.20.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 30,
    name: "Pijama Short Pima Niña",
    price: "S/.20.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 31,
    name: "Pijama Juego Manga Corta Algodón",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 32,
    name: "Pijama Juego Manga Corta Algodón",
    price: "S/.36.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 33,
    name: "Pijama Juego Manga Larga Algodón",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 34,
    name: "Pijama Juego Manga Larga Algodón",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 35,
    name: "Pijama Juego Pima Manga Larga",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 36,
    name: "Pijama Juego Pima Manga Corta",
    price: "S/.43.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 37,
    name: "Pijama Juego 3 Piezas",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.wine, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.rosewood, image: "images/products/orange-1.jpg" },
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 38,
    name: "Pijama Bata Algodón Manga Corta",
    price: "S/.17.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 39,
    name: "Pijama Bata Algodón Manga Larga",
    price: "S/.18.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 40,
    name: "Pijama Bata Franela",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 41,
    name: "Pijama Bata Polar",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.rosewood, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 42,
    name: "Pijama Bata Polar Levantar Hombre",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.antike, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 43,
    favorite: true,
    name: "Pijama Bata Polar Levantar Dama",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 44,
    name: "Pijama Bata Algodón Levantar Hombre",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 45,
    name: "Pijama Bata Algodón Levantar Dama",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 46,
    name: "Pijama Bata Felpa Hombre",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.skyBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.white, image: "images/products/orange-1.jpg" },
      { ...COLORS.wine, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 47,
    name: "Pijama Bata Felpa Dama",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.coral, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 48,
    name: "Pijama Pima Niño #16",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.azuline, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 49,
    name: "Pijama Pima Niña #16",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [],
  },
  {
    id: 50,
    favorite: true,
    name: "Pijama Algodón Niño #16",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 51,
    name: "Pijama Algodón Niña #16",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.corn, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 52,
    name: "Pijama Polar Niño #16",
    price: "S/.23.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 53,
    name: "Pijama Polar Niña #16",
    price: "S/.23.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 54,
    name: "Pijama Short Pima #16",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 55,
    name: "Juego Chamús Dama",
    price: "S/.55.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.wine, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 56,
    favorite: true,
    name: "Juego Chamús Short Dama",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.wine, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 57,
    name: "Pijama Abierta Algodón Hombre",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 58,
    name: "Pijama Abierta Algodón Dama",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 59,
    name: "Pijama Abierta Algodón Manga Corta Pantalón Largo Hombre",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 60,
    favorite: true,
    name: "Pijama Abierta Algodón Manga Corta Pantalón Largo Dama",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 61,
    name: "Pijama Abierta Franela Hombre",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 62,
    favorite: true,
    name: "Pijama Abierta Franela Dama",
    price: "S/.40.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 63,
    name: "Pijama Abierta Polar Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 64,
    name: "Pijama Abierta Polar Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 65,
    name: "Pijama Polar XL Hombre",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 66,
    name: "Pijama Polar XL Dama",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 67,
    name: "Pijama Franela XL Hombre",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 68,
    name: "Pijama Franela XL Dama",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 69,
    name: "Pijama Polar Abierta XL Hombre",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 70,
    name: "Pijama Polar Abierta XL Dama",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 71,
    name: "Pijama Bata y Camisón Polar XL",
    price: "S/.28.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 72,
    name: "Pijama Algodón Manga Larga XL Hombre",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 73,
    name: "Pijama Algodón Manga Larga XL Dama",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.corn, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 74,
    disabled: true,
    name: "Pijama Peluche Dama",
    price: "-",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [],
  },
  {
    id: 75,
    disabled: true,
    name: "Pijama Peluche Salida Dama",
    price: "-",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [],
  },
  {
    id: 76,
    name: "Pijama Short Algodón XL Hombre",
    price: "S/.28.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 77,
    name: "Pijama Short Algodón XL Dama",
    price: "S/.28.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 78,
    name: "Pijama Short Algodón #16 Niño",
    price: "S/.17.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 79,
    name: "Pijama Short Algodón #16 Niña",
    price: "S/.17.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 80,
    name: "Pijama Franela #16 Niño",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 81,
    name: "Pijama Franela #16 Niña",
    price: "S/.30.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["16"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 82,
    name: "Pijama Bata Algodón XL Manga Corta",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 83,
    name: "Pijama Bata Algodón XL Manga Larga",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 84,
    name: "Pijama Algodón Manga Corta Pantalón Largo XL Hombre",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 85,
    name: "Pijama Algodón Manga Corta Pantalón Largo XL Dama",
    price: "S/.32.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 86,
    disabled: true,
    name: "Pijama Short Pima XL Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [],
  },
  {
    id: 87,
    name: "Pijama Short Pima XL Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 88,
    name: "Pijama Short Algodón Abierta Hombre",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 89,
    name: "Pijama Short Algodón Abierta Dama",
    price: "S/.27.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 90,
    name: "Pijama Algodón Manga Corta Pantalón Largo Abierta Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 91,
    name: "Pijama Algodón Manga Corta Pantalón Largo Abierta Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 92,
    name: "Pijama Algodón Manga Larga XL Abierta Hombre",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 93,
    name: "Pijama Algodón Manga Larga XL Abierta Dama",
    price: "S/.35.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 94,
    name: "Bata Franela XL",
    price: "S/.28.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 95,
    disabled: true,
    name: "Franela Bebé Pima",
    price: "S/.22.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["0", "2"],
    colors: [],
  },
  {
    id: 96,
    name: "Pima Abierto Dama",
    price: "S/.37.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 97,
    name: "Pijama Franela XL Abierta Hombre",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.italianBlue, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 98,
    name: "Pijama Franela XL Abierta Dama",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/orange-1.jpg" },
      { ...COLORS.lilac, image: "images/products/orange-1.jpg" },
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
      { ...COLORS.waterGreen, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 99,
    disabled: true,
    name: "Pijama Pima XL Hombre",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [],
  },
  {
    id: 100,
    name: "Pijama Pima XL Dama",
    price: "S/.45.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/orange-1.jpg" },
      { ...COLORS.turquoise, image: "images/products/orange-1.jpg" },
      { ...COLORS.melon, image: "images/products/orange-1.jpg" },
      { ...COLORS.bubblegum, image: "images/products/orange-1.jpg" },
    ],
  },
  {
    id: 101,
    name: "Pijama Abierta Niños Algodón",
    price: "S/.25.00",
    mainImage: "images/products/orange-1.jpg",
    hoverImage: "images/products/orange-1.jpg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.lead, image: "images/products/orange-1.jpg" },
      { ...COLORS.blue, image: "images/products/orange-1.jpg" },
      { ...COLORS.steel, image: "images/products/orange-1.jpg" },
      { ...COLORS.leaf, image: "images/products/orange-1.jpg" },
    ],
  },
];

export const INVENTORY = PRODUCTS.filter((p) => !p.disabled);
export const BEST_PRODUCTS = PRODUCTS.filter((p) => p.favorite);
