import { Product } from "./types";
import { COLORS } from "./constants";

export const PRODUCTS: Product[] = [
  {
    id: 1,
    favorite: true,
    name: "Pijama Algodón Dama",
    slug: "pijama-algodon-dama",
    price: "S/.25.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.melon, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 2,
    favorite: true,
    name: "Pijama Algodón Hombre",
    slug: "pijama-algodon-hombre",
    price: "S/.26.00",
    gender: "hombre",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 3,
    favorite: true,
    name: "Pijama Algodón Niño",
    slug: "pijama-algodon-nino",
    price: "S/.17.00",
    gender: "niño",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.steel, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 4,
    favorite: true,
    name: "Pijama Algodón Niña",
    slug: "pijama-algodon-nina",
    price: "S/.17.00",
    gender: "niña",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.melon, image: "images/products/product-8.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 5,
    favorite: true,
    name: "Pijama Pima Dama",
    slug: "pijama-pima-dama",
    price: "S/.37.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-6.jpeg" },
      { ...COLORS.melon, image: "images/products/product-7.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.corn, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 6,
    favorite: true,
    name: "Pijama Pima Hombre",
    slug: "pijama-pima-hombre",
    price: "S/.37.00",
    gender: "hombre",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.skyBlue, image: "images/products/product-4.jpeg" },
      { ...COLORS.lead, image: "images/products/product-5.jpeg" },
      { ...COLORS.antike, image: "images/products/product-6.jpeg" },
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 7,
    name: "Pijama Pima Niño",
    slug: "pijama-pima-nino",
    price: "S/.25.00",
    gender: "niño",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/product-3.jpeg" },
      { ...COLORS.blue, image: "images/products/product-4.jpeg" },
      { ...COLORS.skyBlue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 8,
    name: "Pijama Pima Niña",
    slug: "pijama-pima-nina",
    price: "S/.25.00",
    gender: "niña",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.melon, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 9,
    name: "Pijama Franela Dama",
    slug: "pijama-franela-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
      { ...COLORS.melon, image: "images/products/product-1.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 10,
    name: "Pijama Franela Hombre",
    slug: "pijama-franela-hombre",
    price: "S/.37.00",
    gender: "hombre",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-6.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-7.jpeg" },
      { ...COLORS.lead, image: "images/products/product-8.jpeg" },
      { ...COLORS.steel, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 11,
    favorite: true,
    name: "Pijama Franela Niño",
    slug: "pijama-franela-nino",
    price: "S/.27.00",
    gender: "niño",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
      { ...COLORS.steel, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 12,
    name: "Pijama Franela Niña",
    slug: "pijama-franela-nina",
    price: "S/.27.00",
    gender: "niña",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.melon, image: "images/products/product-4.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 13,
    favorite: true,
    name: "Pijama Polar Dama",
    slug: "pijama-polar-dama",
    price: "S/.27.00",
    gender: "mujer",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.coral, image: "images/products/product-1.jpeg" },
      { ...COLORS.barnie, image: "images/products/product-2.jpeg" },
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 14,
    name: "Pijama Polar Hombre",
    slug: "pijama-polar-hombre",
    price: "S/.27.00",
    gender: "hombre",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-8.jpeg" },
      { ...COLORS.maroon, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.antike, image: "images/products/product-3.jpeg" },
      { ...COLORS.militaryGreen, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 15,
    name: "Pijama Polar Niño",
    slug: "pijama-polar-nino",
    price: "S/.22.00",
    gender: "niño",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/product-7.jpeg" },
      { ...COLORS.blue, image: "images/products/product-8.jpeg" },
      { ...COLORS.skyBlue, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 16,
    name: "Pijama Polar Niña",
    slug: "pijama-polar-nina",
    price: "S/.22.00",
    gender: "niña",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
      { ...COLORS.fuchsia, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 17,
    name: "Pijama Pantalón Largo M/ corta Algodón Dama",
    slug: "pijama-pantalon-largo-manga-corta-algodon-dama",
    price: "S/.24.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-6.jpeg" },
      { ...COLORS.melon, image: "images/products/product-7.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 18,
    name: "Pijama Pantalón Largo M/corta Algodón Hombre",
    slug: "pijama-pantalon-largo-manga-corta-algodon-hombre",
    price: "S/.25.00",
    gender: "hombre",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
      { ...COLORS.steel, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 19,
    name: "Pijama Pantalón Largo M/corta Pima Dama",
    slug: "pijama-pantalon-largo-manga-corta-pima-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.melon, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 20,
    name: "Pijama Pantalón Largo M/corta Pima Hombre",
    slug: "pijama-pantalon-largo-manga-corta-pima-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 21,
    name: "Pijama Algodón Dama Chavo",
    slug: "pijama-algodon-dama-chavo",
    price: "S/.22.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
      { ...COLORS.melon, image: "images/products/product-2.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-3.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 22,
    name: "Pijama Pima Dama Chavo",
    slug: "pijama-pima-dama-chavo",
    price: "S/.30.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
      { ...COLORS.melon, image: "images/products/product-1.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 23,
    name: "Pijama Short Algodón Dama",
    slug: "pijama-short-algodon-dama",
    price: "S/.25.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.melon, image: "images/products/product-8.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 24,
    name: "Pijama Short Algodón Hombre",
    slug: "pijama-short-algodon-hombre",
    price: "S/.23.00",
    gender: "hombre",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-5.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-6.jpeg" },
      { ...COLORS.lead, image: "images/products/product-7.jpeg" },
      { ...COLORS.steel, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 25,
    name: "Pijama Short Algodón Niño",
    slug: "pijama-short-algodon-nino",
    price: "S/.15.00",
    gender: "niño",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
      { ...COLORS.steel, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 26,
    name: "Pijama Short Algodón Niña",
    slug: "pijama-short-algodon-nina",
    price: "S/.15.00",
    gender: "niña",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.melon, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 27,
    name: "Pijama Short Pima Dama",
    slug: "pijama-short-pima-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.melon, image: "images/products/product-4.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
      { ...COLORS.corn, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 28,
    name: "Pijama Short Pima Hombre",
    slug: "pijama-short-pima-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.skyBlue, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.antike, image: "images/products/product-3.jpeg" },
      { ...COLORS.blue, image: "images/products/product-4.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 29,
    name: "Pijama Short Pima Niño",
    slug: "pijama-short-pima-nino",
    price: "S/.20.00",
    gender: "niño",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.azuline, image: "images/products/product-8.jpeg" },
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.skyBlue, image: "images/products/product-2.jpeg" },
      { ...COLORS.lead, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 30,
    name: "Pijama Short Pima Niña",
    slug: "pijama-short-pima-nina",
    price: "S/.20.00",
    gender: "niña",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
      { ...COLORS.melon, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 31,
    name: "Pijama Juego Manga Corta Algodón",
    slug: "pijama-juego-manga-corta-algodon",
    price: "S/.30.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-7.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-8.jpeg" },
      { ...COLORS.melon, image: "images/products/product-1.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 32,
    name: "Pijama Juego Manga Corta Algodón",
    slug: "pijama-juego-manga-corta-algodon-xl",
    price: "S/.36.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
      { ...COLORS.melon, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 33,
    name: "Pijama Juego Manga Larga Algodón",
    slug: "pijama-juego-manga-larga-algodon",
    price: "S/.32.00",
    gender: "mujer",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-4.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
      { ...COLORS.melon, image: "images/products/product-7.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 34,
    name: "Pijama Juego Manga Larga Algodón",
    slug: "pijama-juego-manga-larga-algodon-xl",
    price: "S/.40.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-4.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-5.jpeg" },
      { ...COLORS.melon, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 35,
    name: "Pijama Juego Pima Manga Larga",
    slug: "pijama-juego-pima-manga-larga",
    price: "S/.45.00",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
      { ...COLORS.blue, image: "images/products/product-3.jpeg" },
      { ...COLORS.melon, image: "images/products/product-4.jpeg" },
      { ...COLORS.lead, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 36,
    name: "Pijama Juego Pima Manga Corta",
    slug: "pijama-juego-pima-manga-corta",
    price: "S/.43.00",
    gender: "mujer",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.waterGreen, image: "images/products/product-1.jpeg" },
      { ...COLORS.blue, image: "images/products/product-2.jpeg" },
      { ...COLORS.melon, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 37,
    name: "Pijama Juego 3 Piezas",
    slug: "pijama-juego-3-piezas",
    price: "S/.30.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.wine, image: "images/products/product-8.jpeg" },
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.rosewood, image: "images/products/product-3.jpeg" },
      { ...COLORS.fuchsia, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 38,
    name: "Pijama Bata Algodón Manga Corta",
    slug: "pijama-bata-algodon-manga-corta",
    price: "S/.17.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.melon, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 39,
    name: "Pijama Bata Algodón Manga Larga",
    slug: "pijama-bata-algodon-manga-larga",
    price: "S/.18.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-7.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-8.jpeg" },
      { ...COLORS.melon, image: "images/products/product-1.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 40,
    name: "Pijama Bata Franela",
    slug: "pijama-bata-franela",
    price: "S/.27.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
      { ...COLORS.melon, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 41,
    name: "Pijama Bata Polar",
    slug: "pijama-bata-polar",
    price: "S/.25.00",
    gender: "mujer",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.rosewood, image: "images/products/product-4.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-5.jpeg" },
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 42,
    name: "Pijama Bata Polar Levantar Hombre",
    slug: "pijama-bata-polar-levantar-hombre",
    price: "S/.40.00",
    gender: "hombre",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-3.jpeg" },
      { ...COLORS.skyBlue, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
      { ...COLORS.antike, image: "images/products/product-6.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 43,
    favorite: true,
    name: "Pijama Bata Polar Levantar Dama",
    slug: "pijama-bata-polar-levantar-dama",
    price: "S/.40.00",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-2.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-3.jpeg" },
      { ...COLORS.pink, image: "images/products/product-4.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 44,
    name: "Pijama Bata Algodón Levantar Hombre",
    slug: "pijama-bata-algodon-levantar-hombre",
    price: "S/.27.00",
    gender: "hombre",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.steel, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 45,
    name: "Pijama Bata Algodón Levantar Dama",
    slug: "pijama-bata-algodon-levantar-dama",
    price: "S/.27.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-8.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 46,
    name: "Pijama Bata Felpa Hombre",
    slug: "pijama-bata-felpa-hombre",
    price: "S/.40.00",
    gender: "hombre",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.skyBlue, image: "images/products/product-8.jpeg" },
      { ...COLORS.white, image: "images/products/product-1.jpeg" },
      { ...COLORS.wine, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 47,
    name: "Pijama Bata Felpa Dama",
    slug: "pijama-bata-felpa-dama",
    price: "S/.40.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L", "Standard"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.coral, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 48,
    name: "Pijama Pima Niño #16",
    slug: "pijama-pima-nino-16",
    price: "S/.32.00",
    gender: "niño",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.azuline, image: "images/products/product-5.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-6.jpeg" },
      { ...COLORS.lead, image: "images/products/product-7.jpeg" },
      { ...COLORS.blue, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 49,
    name: "Pijama Pima Niña #16",
    slug: "pijama-pima-nina-16",
    price: "S/.32.00",
    gender: "niña",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["16"],
    colors: [],
  },
  {
    id: 50,
    favorite: true,
    name: "Pijama Algodón Niño #16",
    slug: "pijama-algodon-nino-16",
    price: "S/.22.00",
    gender: "niño",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lead, image: "images/products/product-3.jpeg" },
      { ...COLORS.maroon, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 51,
    name: "Pijama Algodón Niña #16",
    slug: "pijama-algodon-nina-16",
    price: "S/.22.00",
    gender: "niña",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.corn, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-4.jpeg" },
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 52,
    name: "Pijama Polar Niño #16",
    slug: "pijama-polar-nino-16",
    price: "S/.23.00",
    gender: "niño",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.italianBlue, image: "images/products/product-1.jpeg" },
      { ...COLORS.blue, image: "images/products/product-2.jpeg" },
      { ...COLORS.steel, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 53,
    name: "Pijama Polar Niña #16",
    slug: "pijama-polar-nina-16",
    price: "S/.23.00",
    gender: "niña",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
      { ...COLORS.fuchsia, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 54,
    name: "Pijama Short Pima #16",
    slug: "pijama-short-pima-16",
    price: "S/.30.00",
    gender: "niño",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.fuchsia, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 55,
    name: "Juego Chamús Dama",
    slug: "juego-chamus-dama",
    price: "S/.55.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.wine, image: "images/products/product-6.jpeg" },
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 56,
    favorite: true,
    name: "Juego Chamús Short Dama",
    slug: "juego-chamus-short-dama",
    price: "S/.40.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["Standard"],
    colors: [
      { ...COLORS.wine, image: "images/products/product-5.jpeg" },
      { ...COLORS.blue, image: "images/products/product-6.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 57,
    name: "Pijama Abierta Algodón Hombre",
    slug: "pijama-abierta-algodon-hombre",
    price: "S/.32.00",
    gender: "hombre",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-4.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 58,
    name: "Pijama Abierta Algodón Dama",
    slug: "pijama-abierta-algodon-dama",
    price: "S/.32.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-4.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 59,
    name: "Pijama Abierta Algodón Manga Corta Pantalón Largo Hombre",
    slug: "pijama-abierta-algodon-manga-corta-pantalon-largo-hombre",
    price: "S/.30.00",
    gender: "hombre",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 60,
    favorite: true,
    name: "Pijama Abierta Algodón Manga Corta Pantalón Largo Dama",
    slug: "pijama-abierta-algodon-manga-corta-pantalon-largo-dama",
    price: "S/.30.00",
    gender: "mujer",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-1.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 61,
    name: "Pijama Abierta Franela Hombre",
    slug: "pijama-abierta-franela-hombre",
    price: "S/.40.00",
    gender: "hombre",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.maroon, image: "images/products/product-2.jpeg" },
      { ...COLORS.lead, image: "images/products/product-3.jpeg" },
      { ...COLORS.steel, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 62,
    name: "Pijama Abierta Franela Dama",
    slug: "pijama-abierta-franela-dama",
    price: "S/.40.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.melon, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 63,
    name: "Pijama Abierta Polar Hombre",
    slug: "pijama-abierta-polar-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.leaf, image: "images/products/product-6.jpeg" },
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.maroon, image: "images/products/product-8.jpeg" },
      { ...COLORS.lead, image: "images/products/product-1.jpeg" },
      { ...COLORS.steel, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 64,
    name: "Pijama Abierta Polar Dama",
    slug: "pijama-abierta-polar-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-5.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-6.jpeg" },
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 65,
    name: "Pijama Polar XL Hombre",
    slug: "pijama-polar-xl-hombre",
    price: "S/.32.00",
    gender: "hombre",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-4.jpeg" },
      { ...COLORS.blue, image: "images/products/product-5.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-6.jpeg" },
      { ...COLORS.steel, image: "images/products/product-7.jpeg" },
      { ...COLORS.lead, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 66,
    name: "Pijama Polar XL Dama",
    slug: "pijama-polar-xl-dama",
    price: "S/.32.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 67,
    name: "Pijama Franela XL Hombre",
    slug: "pijama-franela-xl-hombre",
    price: "S/.45.00",
    gender: "hombre",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-2.jpeg" },
      { ...COLORS.blue, image: "images/products/product-3.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 68,
    name: "Pijama Franela XL Dama",
    slug: "pijama-franela-xl-dama",
    price: "S/.45.00",
    gender: "mujer",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-1.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-2.jpeg" },
      { ...COLORS.pink, image: "images/products/product-3.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-4.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 69,
    name: "Pijama Polar Abierta XL Hombre",
    slug: "pijama-polar-abierta-xl-hombre",
    price: "S/.37.00",
    gender: "hombre",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-8.jpeg" },
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-2.jpeg" },
      { ...COLORS.steel, image: "images/products/product-3.jpeg" },
      { ...COLORS.lead, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 70,
    name: "Pijama Polar Abierta XL Dama",
    slug: "pijama-polar-abierta-xl-dama",
    price: "S/.37.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-7.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-8.jpeg" },
      { ...COLORS.pink, image: "images/products/product-1.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-2.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 71,
    name: "Pijama Bata y Camisón Polar XL",
    slug: "pijama-bata-y-camison-polar-xl",
    price: "S/.28.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.pink, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 72,
    name: "Pijama Algodón Manga Larga XL Hombre",
    slug: "pijama-algodon-manga-larga-xl-hombre",
    price: "S/.32.00",
    gender: "hombre",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-5.jpeg" },
      { ...COLORS.blue, image: "images/products/product-6.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-7.jpeg" },
      { ...COLORS.steel, image: "images/products/product-8.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 73,
    name: "Pijama Algodón Manga Larga XL Dama",
    slug: "pijama-algodon-manga-larga-xl-dama",
    price: "S/.32.00",
    gender: "mujer",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-4.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-5.jpeg" },
      { ...COLORS.corn, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 74,
    disabled: true,
    name: "Pijama Peluche Dama",
    slug: "pijama-peluche-dama",
    price: "-",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["S", "M", "L"],
    colors: [],
  },
  {
    id: 75,
    disabled: true,
    name: "Pijama Peluche Salida Dama",
    slug: "pijama-peluche-salida-dama",
    price: "-",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["S", "M", "L"],
    colors: [],
  },
  {
    id: 76,
    name: "Pijama Short Algodón XL Hombre",
    slug: "pijama-short-algodon-xl-hombre",
    price: "S/.28.00",
    gender: "hombre",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 77,
    name: "Pijama Short Algodón XL Dama",
    slug: "pijama-short-algodon-xl-dama",
    price: "S/.28.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 78,
    name: "Pijama Short Algodón #16 Niño",
    slug: "pijama-short-algodon-16-nino",
    price: "S/.17.00",
    gender: "niño",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.lead, image: "images/products/product-8.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-1.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-2.jpeg" },
      { ...COLORS.steel, image: "images/products/product-3.jpeg" },
    ],
  },
  {
    id: 79,
    name: "Pijama Short Algodón #16 Niña",
    slug: "pijama-short-algodon-16-nina",
    price: "S/.17.00",
    gender: "niña",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-6.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-7.jpeg" },
      { ...COLORS.pink, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 80,
    name: "Pijama Franela #16 Niño",
    slug: "pijama-franela-16-nino",
    price: "S/.30.00",
    gender: "niño",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-5.jpeg" },
      { ...COLORS.lead, image: "images/products/product-6.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-7.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
      { ...COLORS.steel, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 81,
    name: "Pijama Franela #16 Niña",
    slug: "pijama-franela-16-nina",
    price: "S/.30.00",
    gender: "niña",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["16"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-4.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-5.jpeg" },
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 82,
    name: "Pijama Bata Algodón XL Manga Corta",
    slug: "pijama-bata-algodon-xl-manga-corta",
    price: "S/.25.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 83,
    name: "Pijama Bata Algodón XL Manga Larga",
    slug: "pijama-bata-algodon-xl-manga-larga",
    price: "S/.27.00",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.pink, image: "images/products/product-4.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 84,
    name: "Pijama Algodón Manga Corta Pantalón Largo XL Hombre",
    slug: "pijama-algodon-manga-corta-pantalon-largo-xl-hombre",
    price: "S/.32.00",
    gender: "hombre",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.lead, image: "images/products/product-2.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-3.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.steel, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 85,
    name: "Pijama Algodón Manga Corta Pantalón Largo XL Dama",
    slug: "pijama-algodon-manga-corta-pantalon-largo-xl-dama",
    price: "S/.32.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 86,
    disabled: true,
    name: "Pijama Short Pima XL Hombre",
    slug: "pijama-short-pima-xl-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["XL"],
    colors: [],
  },
  {
    id: 87,
    name: "Pijama Short Pima XL Dama",
    slug: "pijama-short-pima-xl-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-7.jpeg" },
      { ...COLORS.melon, image: "images/products/product-8.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 88,
    name: "Pijama Short Algodón Abierta Hombre",
    slug: "pijama-short-algodon-abierta-hombre",
    price: "S/.27.00",
    gender: "hombre",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-5.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-6.jpeg" },
      { ...COLORS.blue, image: "images/products/product-7.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-8.jpeg" },
      { ...COLORS.lead, image: "images/products/product-1.jpeg" },
    ],
  },
  {
    id: 89,
    name: "Pijama Short Algodón Abierta Dama",
    slug: "pijama-short-algodon-abierta-dama",
    price: "S/.27.00",
    gender: "mujer",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-4.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-5.jpeg" },
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-7.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 90,
    name: "Pijama Algodón Manga Corta Pantalón Largo Abierta Hombre",
    slug: "pijama-algodon-manga-corta-pantalon-largo-abierta-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-3.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-4.jpeg" },
      { ...COLORS.blue, image: "images/products/product-5.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-6.jpeg" },
      { ...COLORS.lead, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 91,
    name: "Pijama Algodón Manga Corta Pantalón Largo Abierta Dama",
    slug: "pijama-algodon-manga-corta-pantalon-largo-abierta-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-2.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-3.jpeg" },
      { ...COLORS.pink, image: "images/products/product-4.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-5.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-6.jpeg" },
    ],
  },
  {
    id: 92,
    name: "Pijama Algodón Manga Larga XL Abierta Hombre",
    slug: "pijama-algodon-manga-larga-xl-abierta-hombre",
    price: "S/.35.00",
    gender: "hombre",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.maroon, image: "images/products/product-1.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-2.jpeg" },
      { ...COLORS.blue, image: "images/products/product-3.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-4.jpeg" },
      { ...COLORS.lead, image: "images/products/product-5.jpeg" },
    ],
  },
  {
    id: 93,
    name: "Pijama Algodón Manga Larga XL Abierta Dama",
    slug: "pijama-algodon-manga-larga-xl-abierta-dama",
    price: "S/.35.00",
    gender: "mujer",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-8.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-1.jpeg" },
      { ...COLORS.pink, image: "images/products/product-2.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-3.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 94,
    name: "Bata Franela XL",
    slug: "bata-franela-xl",
    price: "S/.28.00",
    gender: "mujer",
    mainImage: "images/products/product-5.jpeg",
    hoverImage: "images/products/product-6.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-7.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-8.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-1.jpeg" },
      { ...COLORS.melon, image: "images/products/product-2.jpeg" },
    ],
  },
  {
    id: 95,
    disabled: true,
    name: "Franela Bebé Pima",
    slug: "franela-bebe-pima",
    price: "S/.22.00",
    gender: "bebe",
    mainImage: "images/products/product-4.jpeg",
    hoverImage: "images/products/product-5.jpeg",
    sizes: ["0", "2"],
    colors: [],
  },
  {
    id: 96,
    name: "Pima Abierto Dama",
    slug: "pima-abierto-dama",
    price: "S/.37.00",
    gender: "mujer",
    mainImage: "images/products/product-3.jpeg",
    hoverImage: "images/products/product-4.jpeg",
    sizes: ["S", "M", "L"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-5.jpeg" },
      { ...COLORS.pink, image: "images/products/product-6.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-7.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 97,
    name: "Pijama Franela XL Abierta Hombre",
    slug: "pijama-franela-xl-abierta-hombre",
    price: "S/.45.00",
    gender: "hombre",
    mainImage: "images/products/product-2.jpeg",
    hoverImage: "images/products/product-3.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.blue, image: "images/products/product-4.jpeg" },
      { ...COLORS.lead, image: "images/products/product-5.jpeg" },
      { ...COLORS.italianBlue, image: "images/products/product-6.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-7.jpeg" },
      { ...COLORS.steel, image: "images/products/product-8.jpeg" },
    ],
  },
  {
    id: 98,
    name: "Pijama Franela XL Abierta Dama",
    slug: "pijama-franela-xl-abierta-dama",
    price: "S/.45.00",
    gender: "mujer",
    mainImage: "images/products/product-1.jpeg",
    hoverImage: "images/products/product-2.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.fuchsia, image: "images/products/product-3.jpeg" },
      { ...COLORS.lilac, image: "images/products/product-4.jpeg" },
      { ...COLORS.pink, image: "images/products/product-5.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-6.jpeg" },
      { ...COLORS.waterGreen, image: "images/products/product-7.jpeg" },
    ],
  },
  {
    id: 99,
    disabled: true,
    name: "Pijama Pima XL Hombre",
    slug: "pijama-pima-xl-hombre",
    price: "S/.45.00",
    gender: "hombre",
    mainImage: "images/products/product-8.jpeg",
    hoverImage: "images/products/product-1.jpeg",
    sizes: ["XL"],
    colors: [],
  },
  {
    id: 100,
    name: "Pijama Pima XL Dama",
    slug: "pijama-pima-xl-dama",
    price: "S/.45.00",
    gender: "mujer",
    mainImage: "images/products/product-7.jpeg",
    hoverImage: "images/products/product-8.jpeg",
    sizes: ["XL"],
    colors: [
      { ...COLORS.pink, image: "images/products/product-1.jpeg" },
      { ...COLORS.turquoise, image: "images/products/product-2.jpeg" },
      { ...COLORS.melon, image: "images/products/product-3.jpeg" },
      { ...COLORS.bubblegum, image: "images/products/product-4.jpeg" },
    ],
  },
  {
    id: 101,
    name: "Pijama Abierta Niños Algodón",
    slug: "pijama-abierta-ninos-algodon",
    price: "S/.25.00",
    gender: "niño",
    mainImage: "images/products/product-6.jpeg",
    hoverImage: "images/products/product-7.jpeg",
    sizes: ["4", "6", "8", "10", "12", "14"],
    colors: [
      { ...COLORS.lead, image: "images/products/product-8.jpeg" },
      { ...COLORS.blue, image: "images/products/product-1.jpeg" },
      { ...COLORS.steel, image: "images/products/product-2.jpeg" },
      { ...COLORS.leaf, image: "images/products/product-3.jpeg" },
    ],
  },
];

export const INVENTORY = PRODUCTS.filter((p) => !p.disabled);
export const BEST_PRODUCTS = PRODUCTS.filter((p) => p.favorite);
